{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Per Minute",
   "type": "timeseries",
   "description": "get rate of http_request_duration_seconds_count for last 30 minutes at 15 seconds resolution",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (increase(http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Concurrent Request Per 10 Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_inflight) by (endpoint)",
     "legendFormat": "{{endpoint}} {{method}}"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_count{status_code=~\"4..\"}[1m])) by (status_code, endpoint, method)) / (sum(rate(http_request_duration_seconds_count[1m])) by (status_code, endpoint, method)) * 100",
     "legendFormat": "{{status_code}}: {{endpoint}} {{ method }}"
    },
    {
     "expr": "(sum(rate(http_request_duration_seconds_count{status_code=~\"5..\"}[1m])) by (status_code, endpoint, method)) / (sum(rate(http_request_duration_seconds_count[1m])) by (status_code, endpoint, method)) * 100",
     "legendFormat": "{{status_code}}: {{endpoint}} {{ method }}"
    },
    {
     "expr": "(sum(rate(http_request_duration_seconds_count{status_code=~\"4..\"}[1m])) by (status_code, endpoint, method))",
     "legendFormat": "{{status_code}}: {{endpoint}} {{ method }}"
    }
   ]
  },
  {
   "title": "HTTP Latency 95p",
   "type": "timeseries",
   "description": "in Seconds",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95, \n    sum by (endpoint, method, le) (rate(http_request_duration_seconds_bucket[10m]))\n)",
     "legendFormat": "{{method}}: {{endpoint}} "
    }
   ]
  },
  {
   "title": "HTTP Latency 50p",
   "type": "timeseries",
   "description": "in Seconds",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.5, \n    sum by (endpoint, method, le) (rate(http_request_duration_seconds_bucket[10m]))\n)",
     "legendFormat": "{{method}}: {{endpoint}} "
    }
   ]
  }
 ]
}